hello: hello world!
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss     # 日期格式化
    time-zone: GMT+8                     # 时区
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.199.108:3306/keji?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: liujiajia
  redis:
    host: 192.168.199.108
    port: 6379
    password:

  ## 设定 flyway 属性
  flyway:
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 杀伤力太大了, 应该禁掉.
    cleanDisabled: true
    # 启用或禁用 flyway
    enabled: true
    # 设定 SQL 脚本的目录,多个路径使用逗号分隔, 比如取值为 classpath:db/migration,filesystem:/sql-migrations
    locations: classpath:db-migration-dev
    # 开发环境最好开启 outOfOrder, 生产环境关闭 outOfOrder
    outOfOrder: true
    # 如果指定 schema 包含了其他表,但没有 flyway schema history 表的话, 在执行 flyway migrate 命令之前, 必须先执行 flyway baseline 命令.
    # 设置 spring.flyway.baseline-on-migrate 为 true 后, flyway 将在需要 baseline 的时候, 自动执行一次 baseline.
    baselineOnMigrate: true
    # 指定 baseline 的版本号,缺省值为 1, 低于该版本号的 SQL 文件, migrate 的时候被忽略.
    baselineVersion: 1
    #  metadata 版本控制信息表 默认 flyway_schema_history
    table: wecom_flyway_schema_history

# MP 配置
mybatis-plus:
  type-enums-package: com.yousails.keji.wecom.enums

#配置动态刷新
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    path: /Users/jimmy/logs/test