hello: hello world!
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss     # 日期格式化
    time-zone: GMT+8                     # 时区
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.141.51.92:3306/kejidb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: kejitest
    password: 123456
  #redis服务地址
  redis:
    host: 8.141.51.92
    #端口
    port: 6379
    #设置密码，没有密码为空
    password: pinduoduo123
    #Redis数据库索引（默认为0）
    redis.database: 0
    #连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-wait: -1
        # 连接池中的最小空闲连接
        max-idle: 8
        # 连接超时时间（毫秒）
        min-idle: 0

  ## 设定 flyway 属性
  flyway:
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 杀伤力太大了, 应该禁掉.
    cleanDisabled: true
    # 启用或禁用 flyway
    enabled: true
    # 设定 SQL 脚本的目录,多个路径使用逗号分隔, 比如取值为 classpath:db/migration,filesystem:/sql-migrations
    locations: classpath:db-migration-dev
    # 开发环境最好开启 outOfOrder, 生产环境关闭 outOfOrder
    outOfOrder: true
    # 如果指定 schema 包含了其他表,但没有 flyway schema history 表的话, 在执行 flyway migrate 命令之前, 必须先执行 flyway baseline 命令.
    # 设置 spring.flyway.baseline-on-migrate 为 true 后, flyway 将在需要 baseline 的时候, 自动执行一次 baseline.
    baselineOnMigrate: true
    # 指定 baseline 的版本号,缺省值为 1, 低于该版本号的 SQL 文件, migrate 的时候被忽略.
    baselineVersion: 1
    #  metadata 版本控制信息表 默认 flyway_schema_history
    table: wecom_flyway_schema_history

# MP 配置
mybatis-plus:
  type-enums-package: com.yousails.keji.wecom.enums

#配置动态刷新
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    path: /data/logs/keji-wecom