#redis服务地址
spring:
  redis:
    host: 8.141.51.92
    #端口
    port: 6379
    #设置密码，没有密码为空
    password: pinduoduo123
    #Redis数据库索引（默认为0）
    redis.database: 0
    #连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  # 连接超时时间（毫秒）